name: Frontend Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create kakao.ts
        run: |
          mkdir -p src/config
          echo "export const KAKAO_JS_KEY = '${{ secrets.KAKAO_JS_KEY }}';" > src/config/kakao.ts

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Remove old dist on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo rm -rf /home/ubuntu/dist

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: dist/
          target: /home/ubuntu/
